image: microsoft/dotnet:1.0.0-preview2-sdk

stages:
  - build
  - test

before_script:
  - dotnet --info
  - dotnet restore

build:
  stage: build
  script:
    - dotnet --verbose build src/Anat -f netstandard1.6
  artifacts:
    untracked: true

test:
  stage: test
  dependencies:
    - build
  script:
    - dotnet --verbose test tests/Anat.Tests -f netcoreapp1.0
