
stages:
  - build

build:
  image: microsoft/dotnet:1.1-sdk-msbuild
  stage: build

  script:
    - dotnet --info
    - dotnet restore
    - dotnet build -c Release -f netstandard1.6 src/Anat --version-suffix "aci-$CI_BUILD_ID"
    - dotnet test -c Release tests/Anat.Tests/Anat.Tests.fsproj
    - dotnet pack -c Release --include-symbols --include-source --version-suffix "aci-$CI_BUILD_ID" || true
  artifacts:
    paths:
      - "*/*/obj/project.assets.json"
      - "src/*/bin"
    expire_in: "30 days"
