version: 1.0.{build}
image: Visual Studio 2015
environment:
  matrix:
    - CLI_VERSION: 1.0.0-preview2-003131
    - CLI_VERSION: Latest

install:
  - ps: $url = "https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/$($env:CLI_VERSION)/dotnet-dev-win-x64.$($env:CLI_VERSION.ToLower()).zip"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: $tempFile = [System.IO.Path]::GetTempFileName()
  - ps: (New-Object System.Net.WebClient).DownloadFile($url, $tempFile)
  - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFile, $env:DOTNET_INSTALL_DIR)
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: dotnet --verbose build src/Anat
  - ps: dotnet --verbose test tests/Anat.Tests
  - ps: dotnet --verbose pack src/Anat -c Release

test: off

artifacts:
  - path: '**\*.nupkg'

matrix:
  allow_failures:
    - CLI_VERSION: Latest
